### PR TITLE
Trim whitespaces from search queries

### PR DESCRIPTION
**Pull request by oneEyedSunday**
For https://github.com/frain-dev/convoy/issues/586

### CODE REVIEW

**Comment by Subomi** [comment]
@oneEyedSunday Nice. But we use `gomock` for mocking vs the stubs in this PR. I think @danvixent added some tests already. Can you update so I can merge? :)

**Review by Subomi — CHANGES_REQUESTED** [review]
@oneEyedSunday Nice. But we use `gomock` for mocking vs the stubs in this PR. I think @danvixent added some tests already. Can you update so I can merge? :)

**Comment by oneEyedSunday** [comment]
Yes I saw his MR. I'd check back and update when his is merged.

**Comment by Subomi** [comment]
@oneEyedSunday Cool.

**Comment by oneEyedSunday** [comment]
Updated @Subomi

**Review by Subomi — APPROVED** [review]

**Pull request merged**
