### PR TITLE
final qa updates on core dashboard

### PR DESCRIPTION
**Pull request by Oluwadaminiola**

### CODE REVIEW

**Comment by horlah** [comment]
@Oluwadaminiola Have you reviewed this?

**Comment by Oluwadaminiola** [comment]
> @Oluwadaminiola Have you reviewed this?

yes I have

**Comment by horlah** [comment]
@Oluwadaminiola The filters dropdown should close after selecting an option from the dropdown.

**Comment by Oluwadaminiola** [comment]
> 

done

**Comment by horlah** [comment]
@Oluwadaminiola Please test this, the overlay is still active after closing the dropdown. Test, please.

**Review by horlah — APPROVED** [review]

**Pull request merged**
