### PR TITLE
CLI for server and worker nodes with cluster membership and leader election

### PR DESCRIPTION
**Pull request by ogbanugot**
In this PR:
1. CLI for running separate instances of server and worker nodes.
2. Cluster membership.
3. Leader election (with Consul)
4. Server nodes are elected as a leader within a cluster.
5. Run separate clusters with server nodes (with different ports)
6. Leader election amongst worker nodes to enable a worker switch to an instance of a server node (if the initial server node is down).  
7. Workers can join a cluster through the CLI by specifying a member of the cluster.

### CODE REVIEW

**Comment by ogbanugot** [comment]
I'd love to hear your thoughts on the initial work being done here. We actually need to run events through the distributed architecture to know for sure that things run smoothly. But thoughts on the CLI so far? @Subomi @jirevwe

**Comment by jirevwe** [comment]
Hey @ogbanugot I know this mught be a big ask but can you go through this PR with myself and @Subomi tomorrow?

**Comment by ogbanugot** [comment]
> Hey @ogbanugot I know this might be a big ask but can you go through this PR with myself and @Subomi tomorrow?

Sounds good!

**Review by jirevwe — APPROVED** [review]
Asides those other things we talked about (do we need leader election, will go routines of dead worker complete before becoming a server), it seems ok.

**Comment by ogbanugot** [comment]
Okay cool, I'll merge this and address those in a new PR.

**Comment by Subomi** [comment]
> Okay cool, I'll merge this and address those in a new PR.

👍🏽

**Pull request merged**
