### PR TITLE
Core dahboard review update

### PR DESCRIPTION
**Pull request by Oluwadaminiola**

### CODE REVIEW

**Comment by Oluwadaminiola** [comment]
> Screenshot 2022-04-08 at 3 38 16 PM
> 
> Screenshot 2022-04-08 at 3 44 04 PM
> 
> The date looks scanty on the design here. Please work with JK to find a middle ground here. @Oluwadaminiola

oh Alright @horlah

**Comment by horlah** [comment]
I'm unable to test this. Styles in the UI library is not reflecting @Oluwadaminiola

**Comment by Oluwadaminiola** [comment]
> Screenshot 2022-04-13 at 5 15 20 PM
> 
> I think the date text is missing here @Oluwadaminiola

hmm, this is weird

**Comment by horlah** [comment]
Does it show on your machine? @Oluwadaminiola

**Comment by horlah** [comment]
@Oluwadaminiola Please wait, I found something.

**Comment by Oluwadaminiola** [comment]
> @Oluwadaminiola Please wait, I found something.

okay

**Comment by horlah** [comment]
Screenshot 2022-04-13 at 6 22 27 PM

The pagination number is incorrect. Look at this for example.
I guess a fix to this is getting the length/number of events/data from the API response instead of automatically adding 20. Make sense? @Oluwadaminiola

**Pull request merged**
