### PR TITLE
Pelumi/update/app portal UI sync

### PR DESCRIPTION
**Pull request by Oluwadaminiola**
In this pr, the app portal was brought up to speed to be in sync with the UI Library
The filters were also updated to fit what's on the design

### CODE REVIEW

**Comment by horlah** [comment]
Screenshot 2022-03-14 at 8 09 38 PM

- Please add some space between the endpoint events
- There is a weird space covering the borders on the left and right side of the table body items
- Please disable the capitalization happening on the table items.

@Oluwadaminiola

**Comment by Oluwadaminiola** [comment]
> Screenshot 2022-03-14 at 8 09 38 PM
> 
> * Please add some space between the endpoint events
> * There is a weird space covering the borders on the left and right side of the table body items
> * Please disable the capitalization happening on the table items.
> 
> @Oluwadaminiola

I've made these changes on the UI library, we just need to merge them @horlah

**Comment by Oluwadaminiola** [comment]
> Screenshot 2022-03-14 at 8 09 38 PM
> 
> * Please add some space between the endpoint events
> * There is a weird space covering the borders on the left and right side of the table body items
> * Please disable the capitalization happening on the table items.
> 
> @Oluwadaminiola

I've made these changes on the UI library, we just need to merge them @horlah

**Comment by horlah** [comment]
@Oluwadaminiola please merge them, increase the version number on the package.json file and publish a new version

**Comment by horlah** [comment]
New version number should be 0.0.2 @Oluwadaminiola

**Comment by Oluwadaminiola** [comment]
> New version number should be 0.0.2 @Oluwadaminiola

okay, noted

**Review by horlah — APPROVED** [review]

**Pull request merged**
