### PR TITLE
Format metrics

### PR DESCRIPTION
**Pull request by oneEyedSunday**
For https://github.com/frain-dev/convoy/issues/442

### CODE REVIEW

**Comment by oneEyedSunday** [comment]
I'm running into a problem here though (see https://github.com/frain-dev/convoy/issues/448)
I also cant seem to solely run the test I added (tried "test": "ng test --include=src/app/shared/pipes  --source-map=false")


Also, how do I import stuff from dashboard/shared into dashboard-component
or should this be the other way round?  @horlah

**Comment by oneEyedSunday** [comment]
closes https://github.com/frain-dev/convoy/issues/442

**Comment by horlah** [comment]
> I'm running into a problem here though (see #448) I also cant seem to solely run the test I added (tried "test": "ng test --include=src/app/shared/pipes --source-map=false")
> 
> Also, how do I import stuff from dashboard/shared into dashboard-component or should this be the other way round? @horlah

We're yet to set up the test suite on the Angular application and components, hence the error you're getting.

You should import the pipe you created into the `dashboard-component`'s module, then use it inside the HTML file. Having any trouble or errors with that?

@oneEyedSunday

**Comment by oneEyedSunday** [comment]
Ok id move it

**Comment by oneEyedSunday** [comment]
Moved in https://github.com/frain-dev/convoy/pull/449/commits/36bd54526f66da2db9fff9d773d7978b1c705a17

**Comment by horlah** [comment]
@oneEyedSunday Noticed this PR is against the main branch, I think it should be against `release-0.4` since it's more like a fix, not a new feature.

**Comment by oneEyedSunday** [comment]
Ok

**Comment by oneEyedSunday** [comment]
@horlah  use https://github.com/frain-dev/convoy/pull/452 instead

**Pull request closed without merging**
