### PR TITLE
feat: enable multi-archtecture build for docker

### PR DESCRIPTION
**Pull request by nimboya**
Enable Multi-Architecture to build for convoy docker image

### CODE REVIEW

**Comment by jirevwe** [comment]
Hey @nimboya, apologies for the very delayed reply.

We currently use Goreleaser to build and publish images and that workflow file is a no-op as the workflow itself has been disabled for over a year now.

**Comment by nimboya** [comment]
> Hey @nimboya, apologies for the very delayed reply.
> 
> We currently use Goreleaser to build and publish images and that workflow file is a no-op as the workflow itself has been disabled for over a year now.

Hi @jirevwe 

Does this mean docker images are not build anymore, if they are, is Goreleaser used to build and push it ?

**Comment by jirevwe** [comment]
@nimboya They are being built, Goreleaser is used to build and publish them. See them [here](https://cloudsmith.io/~convoy/repos/convoy/packages)

**Comment by subomi** [comment]
Opened a PR to do this with goreleaser here - #1790

**Pull request closed without merging**
